name: agent_trust
channels:
  - https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - bzip2=1.0.8=hcfcfb64_5
  - ca-certificates=2024.2.2=h56e8100_0
  - libffi=3.4.2=h8ffe710_5
  - libsqlite=3.45.1=hcfcfb64_0
  - libzlib=1.2.13=hcfcfb64_5
  - openssl=3.2.1=hcfcfb64_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.10.13=h4de0772_1_cpython
  - setuptools=69.0.3=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=hcf57466_18
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - pip:
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - altair==5.2.0
      - annotated-types==0.6.0
      - anyio==4.2.0
      - async-timeout==4.0.2
      - attrs==23.1.0
      - beautifulsoup4==4.12.2
      - bs4==0.0.1
      - camel==0.1.0
      - camel-ai==0.1.1
      - certifi==2022.12.7
      - charset-normalizer==3.1.0
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.1.0
      - cycler==0.11.0
      - exceptiongroup==1.2.0
      - fastapi==0.109.2
      - ffmpy==0.3.1
      - filelock==3.13.1
      - fonttools==4.42.1
      - frozenlist==1.3.3
      - fsspec==2023.10.0
      - gradio==4.18.0
      - gradio-client==0.10.0
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.19.4
      - idna==3.4
      - importlib-resources==6.1.1
      - instructor==0.5.2
      - jinja2==3.1.3
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - kiwisolver==1.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.2
      - mdurl==0.1.2
      - multidict==6.0.4
      - numpy==1.24.3
      - openai==1.12.0
      - orjson==3.9.13
      - packaging==23.1
      - pandas==2.2.0
      - pathlib==1.0.1
      - pillow==10.0.0
      - protobuf==4.25.2
      - pydantic==2.6.1
      - pydantic-core==2.16.2
      - pydub==0.25.1
      - pygments==2.17.2
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-multipart==0.0.9
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.30.2
      - regex==2023.3.23
      - requests==2.31.0
      - rpds-py==0.9.2
      - ruff==0.2.1
      - safetensors==0.4.1
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - starlette==0.36.3
      - tenacity==8.2.3
      - tiktoken==0.3.3
      - tokenizers==0.15.0
      - tomlkit==0.12.0
      - toolz==0.12.1
      - tqdm==4.65.0
      - transformers==4.35.2
      - typer==0.9.0
      - types-colorama==0.4.15.20240205
      - types-requests==2.31.0.20240125
      - typing-extensions==4.8.0
      - tzdata==2024.1
      - urllib3==2.2.0
      - uvicorn==0.27.1
      - websockets==11.0.3
      - yarl==1.9.1
prefix: D:\anaconda\envs\agent_trust
